### PR TITLE
Added modules to manage nuget package installs

### PR DESCRIPTION
**Pull request by m03**
**Summary**

* Added execution and state modules to manage NuGet package installation on Windows servers. 

**Testing**

* Tested against Windows 2012r2 with nuget.exe version 3.3.0.212, running salt-minion 2015.5.8.

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks!

**Comment by UtahDave** [comment]
I'd like to see this in salt proper. Any reason not to?

**Comment by gravyboat** [comment]
@UtahDave I can't think of one. There were just a bunch of contrib PRs open and this one looked easy to get in and was a few months old.

**Comment by m03** [comment]
@UtahDave I'm not opposed to it. Just keeping in mind that I wrote this with a fairly narrow application of nuget in mind...it has more command line options and alternate ways of working than what I accounted for here. Still, better to have something than nothing.

**Pull request merged**
