### PR TITLE
Too many arguments for logging format string

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
fixed issue #103

### CODE REVIEW

**Comment by nmadhok** [comment]
@h4ck3rm1k3 Can you change

os.chmod(tmp.name, 0o700) back to 

os.chmod(tmp.name, 0700)

**Comment by h4ck3rm1k3** [comment]
sure, but http://legacy.python.org/dev/peps/pep-3127/ pylint was not happy.

**Comment by h4ck3rm1k3** [comment]
rebased and included the other fixes

**Comment by nmadhok** [comment]
@h4ck3rm1k3 Thanks for the great work! :)

**Pull request merged**
