### PR TITLE
Add zenoss module

### PR DESCRIPTION
**Pull request by iamseth**
Adding a module for controlling Zenoss from a minion.

Currently supports adding a new device and checking if a device is already added.

### CODE REVIEW

**Comment by UtahDave** [comment]
Thanks!

Any reason not to move this to Salt proper? If not, go ahead and open a pull request there.

**Comment by iamseth** [comment]
@UtahDave -  I didn't want to be so bold as to submit to Salt proper straight away :)

I'll work up another pull.

**Comment by UtahDave** [comment]
Ah, don't worry about that.  We usually put things in salt-contrib that we want publicly available, but might not make sense everywhere or might be intrusive in some environments.

I think this zenoss module wouldn't hurt being in Salt proper.

Thanks for the contribution!

**Comment by iamseth** [comment]
Cool, got a pull pending at https://github.com/saltstack/salt/pull/25634

Added a state module as well. Thanks for the quick feedback!

**Pull request merged**
