### PR TITLE
WIP: Initial start at doing pylint fixes #74

### LINKED ISSUE #74: Missing pylint coverage
When checked using Salt's pylintrc, this project has numerous pylint warnings.

### PR DESCRIPTION
**Pull request by arif-ali**
Initial start in getting pylint in.
Taken .pylintrc from the main salt project
Only checking folders that have __init__.py file

Will try to fix all the lint issues here, and then merge in
* [x] runners
* [x] returners
* [x] renderers
* [x] grains
* [ ] states
* [ ] modules

Some things that need doing, that is not under my control (more may need to be added)
* [ ] Enable Travis CI in the repo

Issues still to be fixed
* [ ] `states/smx.py` -- 1 issue
* [ ] `renderers/pyobjects.py` -- 1 issue
* [ ] `modules/win_update` -- 3 issues
* [ ] `states/win_update` -- 5 issues

Full list of all the current lint issues are visible in the following URL

https://gitlab.ocf.co.uk/snippets/80

Fixes issue #74

### CODE REVIEW

**Comment by arif-ali** [comment]
Current list of all pylint issues, anyone who wants to help, then please ping me, such a long and boring job to fix this

https://gitlab.ocf.co.uk/snippets/80

**Comment by arif-ali** [comment]
In the `renderers/pyobjects.py`, which I need to resolve, The only thing I can think of is moving it to the top

```
renderers/pyobjects.py:461: [W0105(pointless-string-statement), ] String statement has no effect
```

**Comment by arif-ali** [comment]
win_update.py lint still gives issues, but from 100s of lines of changes to do, compared to about 8. Some help needed here ;)

```
$ pylint --rcfile=.pylintrc --disable=W1307,str-format-in-logging modules/win_update.py states/win_update.py 
Using config file /Users/arif/gitRepos/salt/salt-contrib/.pylintrc
************* Module modules.win_update
modules/win_update.py:92: [C1001(old-style-class), PyWinUpdater] Old-style class defined.
modules/win_update.py:308: [E0602(undefined-variable), PyWinUpdater.GetDownloadResults] Undefined variable 'updates'
modules/win_update.py:312: [E0602(undefined-variable), PyWinUpdater.GetDownloadResults] Undefined variable 'updates'
************* Module states.win_update
states/win_update.py:101: [C1001(old-style-class), PyWinUpdater] Old-style class defined.
states/win_update.py:250: [E0602(undefined-variable), PyWinUpdater.GetInstallationResults] Undefined variable 'updates'
states/win_update.py:256: [E0602(undefined-variable), PyWinUpdater.GetInstallationResults] Undefined variable 'updates'
states/win_update.py:264: [E0602(undefined-variable), PyWinUpdater.GetDownloadResults] Undefined variable 'updates'
states/win_update.py:268: [E0602(undefined-variable), PyWinUpdater.GetDownloadResults] Undefined variable 'updates'
```

**Comment by tpoonach** [comment]
I am not original author

**Comment by rallytime** [comment]
@arif-ali I didn't notice this before, but if you use the `.testing.pylintrc` in the salt repo, the number of errors won't be as numerous. That's the file we use for our jenkins tests over there. We use that one because there are several things that we don't care to warn about as much.

Switching over to using taht file should help with this effort, and I would say we should be using that one moving forward in this repo, once automated lint runs are established.

**Comment by arif-ali** [comment]
@rallytime, it's the same i.e. I got the one from `.testing.pylintrc` and just added one line. In-fact, if I now download the one from saltstack/salt, this the diff I get from my repo. So in essence, it's the same

```diff
diff --git a/.pylintrc b/.pylintrc
index 4e86041..832ff81 100644
--- a/.pylintrc
+++ b/.pylintrc
@@ -40,7 +40,7 @@ extension-pkg-whitelist=
 
 # Fileperms Lint Plugin Settings
 fileperms-default=0644
-fileperms-ignore-paths=_modules/*.py,_states/*.py
+fileperms-ignore-paths=setup.py,tests/runtests.py,tests/jenkins*.py,tests/saltsh.py,tests/buildpackage.py
 
 # Minimum Python Version To Enforce
 minimum-python-version = 2.7
@@ -55,8 +55,7 @@ allowed-3rd-party-modules = msgpack,
   libcloud,
   zmq,
   pytest,
-  pytestsalt,
-  salt
+  pytestsalt
 
 [MESSAGES CONTROL]
 # Only show warnings with the listed confidence levels. Leave empty to show
```

There are loads of stuff. The snippet I have in the main description the length of errors was about 4000 lines from all the modules. Now more closer to 2000, I will get to the end ;)

**Comment by rallytime** [comment]
Ah, ok. Thank you so much for your effort here @arif-ali!

**Comment by arif-ali** [comment]
Thanks @wyardley, I'll rebase, and continue on. 

Atom is text editor, which can handle pep8 python lint automatically, so that I can see all the errors in line, and don't have to keep going to the CLI to check. So it just quickly allowed me to go through and fix everything that was obvious.

I still now need to go through the rest (via CLI), and fix those. I have a snippet in a link, with all the current issues in the top post.

**Comment by UtahDave** [comment]
Hey, @arif-ali Thanks so much for doing this pylint work. It's incredibly helpful!

When managing PRs for a large project like Salt often times having to review a huge PR that touches many files is difficult to do quickly and accurately.  Would you be willing to rebase this current PR so we can merge it, and then open up new PRs that modify 10 files or so at a time? That way we can review and merge these fixes quickly and avoid merge conflicts.

What do you think?

**Comment by wyardley** [comment]
@arif-ali Also, might see how much mileage `autopep8` or something similar will give you - might need a few adjustments, but, having done some things both ways recently, I can tell you that doing everything by hand is going to be mighty laborious!

**Pull request merged**
